# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-19 05:03
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', DjangoUeditor.models.UEditorField(max_length=200000, verbose_name='content')),
                ('date', models.DateField(auto_now_add=True, verbose_name='create_date')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
            ],
            options={
                'verbose_name': 'comment \u8bc4\u8bba',
                'verbose_name_plural': 'comment \u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Encyclopedia_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', DjangoUeditor.models.UEditorField(max_length=200000, verbose_name='content')),
                ('date', models.DateField(auto_now_add=True, verbose_name='create_date')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
            ],
            options={
                'verbose_name': 'encyclopedia \u767e\u79d1',
                'verbose_name_plural': 'encyclopedia \u767e\u79d1',
            },
        ),
    ]
