# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-19 05:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_article',
            name='time',
            field=models.DateField(default=datetime.datetime(2018, 8, 19, 5, 51, 3, 367411, tzinfo=utc), verbose_name='publish_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encyclopedia_article',
            name='time',
            field=models.DateField(default=datetime.datetime(2018, 8, 19, 5, 51, 14, 847484, tzinfo=utc), verbose_name='publish_time'),
            preserve_default=False,
        ),
    ]
