# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-21 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180819_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_article',
            name='description',
            field=models.TextField(default='', max_length=10000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encyclopedia_article',
            name='description',
            field=models.TextField(default='', max_length=10000, verbose_name='description'),
            preserve_default=False,
        ),
    ]
