# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-27 00:33
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180821_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', DjangoUeditor.models.UEditorField(max_length=200000, verbose_name='content')),
                ('description', models.TextField(max_length=10000, verbose_name='description')),
                ('date', models.DateField(auto_now_add=True, verbose_name='create_date')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('time', models.DateField(verbose_name='publish_time')),
            ],
            options={
                'verbose_name': 'announcement \u516c\u544a',
                'verbose_name_plural': 'announcement \u516c\u544a',
            },
        ),
    ]
